INSERT INTO livro (titulo_livro, autor_livro, ano_publicacao) VALUES
    ('Dom Quixote', 'Miguel de Cervantes', 1605),
    ('Orgulho e Preconceito', 'Jane Austen', 1813),
    ('Moby Dick', 'Herman Melville', 1851),
    ('Guerra e Paz', 'Lev Tolstói', 1869),
    ('Cem Anos de Solidão', 'Gabriel García Márquez', 1967),
    ('1984', 'George Orwell', 1949),
    ('Ulisses', 'James Joyce', 1922),
    ('A Divina Comédia', 'Dante Alighieri', 1320),
    ('O Apanhador no Campo de Centeio', 'J.D. Salinger', 1951),
    ('Crime e Castigo', 'Fiódor Dostoiévski', 1866),
    ('O Senhor dos Anéis', 'J.R.R. Tolkien', 1954),
    ('A Revolução dos Bichos', 'George Orwell', 1945),
    ('O Grande Gatsby', 'F. Scott Fitzgerald', 1925),
    ('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 1943),
    ('Hamlet', 'William Shakespeare', 1603),
    ('A Metamorfose', 'Franz Kafka', 1915),
    ('Os Miseráveis', 'Victor Hugo', 1862),
    ('O Retrato de Dorian Gray', 'Oscar Wilde', 1890),
    ('A Odisséia', 'Homero', 0),
    ('Anna Karenina', 'Lev Tolstói', 1877);
